### ISSUE TITLE
hyphenated flags break color scheme

### ISSUE THREAD

**Issue by 0pcom** [ivanpirog/coloredcobra#1]
i found coloredcobra within the first week of its presence on github, serendipitously.

its now used in [skycoin/skywire develop](https://github.com/skycoin/skywire/tree/develop) and im very satisfied with its impact on the help menus.

While i was implementing it, I noticed that the color scheme breaks at the hyphen for any flags which contain a hyphen (i.e. --hyphen-flag) with the text returning to white at the hyphen until the end of the flag text.

I neglected to file an issue on this when i encountered it, and instead i just removed the hyphenation of the flags to avoid breaking the color scheme.

Also, there seems to be no way to change the color of the variable type the flag takes, or the color for the default value of the flag,  if it is displayed. 

i further worked around that by not initially setting a default value for certain flags, and showing the default as part of the help text where possible. There were other functional reasons for doing this so it wasnt all an asthetic consideration.

Some screenshots of the help menus, in case you are interested

![image](https://user-images.githubusercontent.com/36607567/173238324-5fc238c8-f28b-4ed9-a0a7-097ddd09a398.png)

![image](https://user-images.githubusercontent.com/36607567/173238436-f7142390-77e5-4fe6-866b-99de18cc1aac.png)

This one shows what i was talking about with the default value

![image](https://user-images.githubusercontent.com/36607567/173238520-c4656e4d-5734-4061-85d3-107a5a14f508.png)

coloredcobra is a fantastic addition to any cobra help menu, and i highly recommend it.

**Comment by ivanpirog** [comment]
> While i was implementing it, I noticed that the color scheme breaks at the hyphen for any flags which contain a hyphen (i.e. --hyphen-flag) with the text returning to white at the hyphen until the end of the flag text.

Hmm... It's very strange because I don't see any breaks of color scheme.

What version do you use? Because this bug was in 1.0.0. And already fixed in 1.0.1 :)

**Comment by ivanpirog** [comment]
> Also, there seems to be no way to change the color of the variable type the flag takes, or the color for the default value of the flag, if it is displayed.

I have no problems with color of the variable type in v1.0.1.
```
cc.Init(&cc.Config{
		RootCmd:       rootCmd,
		Headings:      cc.HiCyan + cc.Bold + cc.Underline,
		Commands:      cc.HiYellow + cc.Bold,
		Aliases:       cc.Bold + cc.Italic,
		CmdShortDescr: cc.HiRed,
		Example:       cc.Italic,
		ExecName:      cc.Bold,
		Flags:         cc.Bold,
		FlagsDescr:    cc.HiRed,
		FlagsDataType: cc.Italic + cc.HiBlue,
	})
```
Result is:

![image](https://user-images.githubusercontent.com/8699212/173918084-44e452e8-93d0-4a63-a69d-a5c74fd28e22.png)

Try: FlagsDataType: cc.Italic + cc.HiBlue,

**Comment by ivanpirog** [comment]
Please look in `go.mod`. What version of coloredcobra?
